
TLDs = {
    ".com":  ["whois.verisign-grs.com","whois.crsnic.net"],
    ".net":  ["whois.verisign-grs.com","whois.crsnic.net"],
    ".org":  ["whois.pir.org", "whois.publicinterestregistry.net"],
    ".info":  ["whois.afilias.info", "whois.afilias.net"],
    ".biz":  "whois.neulevel.biz",
    ".us":  "whois.nic.us",
    ".il.us":"whois.nic.us",
    ".uk":  "whois.nic.uk",
    ".co.uk":"whois.nic.uk",
    ".org.uk":"whois.nic.uk",
    ".gov.uk":"whois.nic.uk",
    ".me.uk":"whois.nic.uk",
    ".ca":  "whois.cira.ca",
    ".bc.ca": "whois.cira.ca",
    ".on.ca":"whois.cira.ca",
    ".qc.ca":"whois.cira.ca",
    ".gc.ca":"whois.cira.ca",
    ".tel":  "whois.nic.tel",
    ".ie":  ["whois.iedr.ie", "whois.domainregistry.ie"],
    ".it":  "whois.nic.it",
    ".li":  "whois.nic.li",
    ".no":  "whois.norid.no",
    ".vgs.no":"whois.norid.no",
    ".folkebibl.no":"whois.norid.no",
    ".cc":  "whois.nic.cc",
    ".eu":  "whois.eu",
    ".nu":  "whois.nic.nu",
    ".com.au":  "whois.audns.net.au",
    ".org.au":  "whois.audns.net.au",
    ".de":  "whois.denic.de",
    ".ws":  ["whois.worldsite.ws", "whois.nic.ws", "www.nic.ws"],
    ".sc":  "whois2.afilias-grs.net",
    ".mobi":  "whois.dotmobiregistry.net",
    ".pro":  ["whois.registrypro.pro", "whois.registry.pro"],
    ".edu":  ["whois.educause.net", "whois.crsnic.net"],
    ".tv":  ["whois.nic.tv", "tvwhois.verisign-grs.com"],
    ".travel":  "whois.nic.travel",
    ".name":  "whois.nic.name",
    ".in":  ["whois.inregistry.net", "whois.registry.in"],
    ".gov.in":["whois.inregistry.net", "whois.registry.in"],
    ".nic.in":["whois.inregistry.net", "whois.registry.in"],
    ".co.in":["whois.inregistry.net", "whois.registry.in"],
    ".me":  ["whois.nic.me", "whois.meregistry.net"],
    ".at":  "whois.nic.at",
    ".be":  "whois.dns.be",
    ".cn":  ["whois.cnnic.cn", "whois.cnnic.net.cn"],
    ".gov.cn":["whois.cnnic.cn", "whois.cnnic.net.cn"],
    ".edu.cn": "whois.edu.cn",
    ".net.cn": "whois.cnnic.cn",
    ".com.cn": "whois.cnnic.cn",
    ".sh.cn":"whois.cnnic.cn",
    ".asia":  "whois.nic.asia",
    ".ru":  ["whois.ripn.ru", "whois.ripn.net"],
    ".msk.ru":["whois.ripn.ru", "whois.ripn.net"],
    ".ro":  "whois.rotld.ro",
    ".aero":  "whois.aero",
    ".fr":  "whois.nic.fr",
    ".se":  ["whois.iis.se", "whois.nic-se.se", "whois.nic.se"],
    ".nl":  ["whois.sidn.nl", "whois.domain-registry.nl"],
    ".nz":  ["whois.srs.net.nz", "whois.domainz.net.nz"],
    ".mx":  "whois.nic.mx",
    ".com.mx":"whois.nic.mx",
    ".gob.mx":"whois.nic.mx",
    ".tw":  "whois.twnic.net.tw",
    ".com.tw":"whois.twnic.net.tw",
    ".edu.tw":"whois.twnic.net.tw",
    ".gov.tw":"whois.twnic.net.tw",
    ".ch":  "whois.nic.ch",
    ".hk":  "whois.hknic.net.hk",
    ".com.hk":"whois.hknic.net.hk",
    ".ac":  "whois.nic.ac",
    ".ae":  "whois.aeda.net.ae",
    ".af":  "whois.nic.af",
    ".ag":  "whois.nic.ag",
    ".al":  "whois.ripe.net",
    ".am":  "whois.amnic.net",
    ".as":  "whois.nic.as",
    ".az":  "whois.ripe.net",
    ".ba":  "whois.ripe.net",
    ".bg":  "whois.register.bg",
    ".bi":  "whois.nic.bi",
    ".bj":  "www.nic.bj",
    ".br":  "whois.nic.br",
    ".com.br": "whois.nic.br",
    ".pro.br":"whois.nic.br",
    ".org.br":"whois.nic.br",
    ".jus.br":"whois.nic.br",
    ".eu.org": "whois.eu.org",
    ".bt":  "whois.netnames.net",
    ".by":  "whois.cctld.by",
    ".bz":  "whois.belizenic.bz",
    ".cd":  "whois.nic.cd",
    ".ck":  "whois.nic.ck",
    ".cl":  "whois.nic.cl",
    ".coop": "whois.nic.coop",
    ".cx":  "whois.nic.cx",
    ".cy":  "whois.ripe.net",
    ".cz":  "whois.nic.cz",
    ".dk":  "whois.dk-hostmaster.dk",
    ".dm":  "whois.nic.cx",
    ".dz":  "whois.ripe.net",
    ".ee":  "whois.eenet.ee",
    ".eg":  "whois.ripe.net",
    ".es":  "whois.nic.es",
    ".com.es":"whois.nic.es",
    ".fi":  "whois.ficora.fi",
    ".fo":  "whois.ripe.net",
    ".gb":  "whois.ripe.net",
    ".ge":  "whois.ripe.net",
    ".gl":  "whois.ripe.net",
    ".gm":  "whois.ripe.net",
    ".gov":  "whois.nic.gov",
    ".gr":  "whois.ripe.net",
    ".gs":  "whois.adamsnames.tc",
    ".hm":  "whois.registry.hm",
    ".hn":  "whois2.afilias-grs.net",
    ".hr":  "whois.ripe.net",
    ".hu":  "whois.ripe.net",
    ".il":  "whois.isoc.org.il",
    ".co.il":"whois.isoc.org.il",
    ".int":  "whois.isi.edu",
    ".iq":  "vrx.net",
    ".ir":  "whois.nic.ir",
    ".gov.ir":"whois.nic.ir",
    ".is":  "whois.isnic.is",
    ".je":  "whois.je",
    ".jp":  "whois.jprs.jp",
    ".co.jp":"whois.jprs.jp",
    ".or.jp":"whois.jprs.jp",
    ".ac.jp":"whois.jprs.jp",
    ".ne.jp":"whois.jprs.jp",
    ".go.jp":"whois.jprs.jp",
    ".kg":  "whois.domain.kg",
    ".kr":  "whois.nic.or.kr",
    ".or.kr":"whois.nic.or.kr",
    ".co.kr":"whois.nic.or.kr",
    ".go.kr":"whois.nic.or.kr",
    ".ac.kr":"whois.nic.or.kr",
    ".la":  "whois2.afilias-grs.net",
    ".lt":  "whois.domreg.lt",
    ".lu":  "whois.restena.lu",
    ".lv":  "whois.nic.lv",
    ".ly":  "whois.lydomains.com",
    ".ma":  "whois.iam.net.ma",
    ".mc":  "whois.ripe.net",
    ".md":  "whois.nic.md",
    ".mil":  "whois.nic.mil",
    ".mk":  "whois.ripe.net",
    ".ms":  "whois.nic.ms",
    ".mt":  "whois.ripe.net",
    ".mu":  "whois.nic.mu",
    ".my":  "whois.mynic.my",
    ".com.my":"whois.mynic.my",
    ".edu.my":"whois.mynic.my",
    ".gov.my":"whois.mynic.my",
    ".nf":  "whois.nic.cx",
    ".pl":  "whois.dns.pl",
    ".com.pl":"whois.dns.pl",
    ".net.pl":"whois.dns.pl",
    ".org.pl":"whois.dns.pl",
    ".edu.pl":"whois.dns.pl",
    ".pr":  "whois.nic.pr",
    ".pt":  "whois.dns.pt",
    ".gov.sa":  ["saudinic.net.sa","whois.nic.net.sa"],
    ".com.sa":  ["saudinic.net.sa","whois.nic.net.sa"],
    ".med.sa":  ["saudinic.net.sa","whois.nic.net.sa"],
    ".edu.sa":  ["saudinic.net.sa","whois.nic.net.sa"],
    ".sa":  ["saudinic.net.sa","whois.nic.net.sa"],
    ".sb":  "whois.nic.net.sb",
    ".sg":  "whois.nic.net.sg",
    ".com.sg":"whois.nic.net.sg",
    ".gov.sg":"whois.nic.net.sg",
    ".sh":  "whois.nic.sh",
    ".si":  "whois.arnes.si",
    ".sk":  "whois.sk-nic.sk",
    ".sm":  "whois.ripe.net",
    ".st":  "whois.nic.st",
    ".su":  "whois.ripn.net",
    ".tc":  "whois.adamsnames.tc",
    ".tf":  "whois.nic.tf",
    ".th":  "whois.thnic.net",
    ".tj":  "whois.nic.tj",
    ".tk":  "whois.nic.tk",
    ".tl":  "whois.domains.tl",
    ".tm":  "whois.nic.tm",
    ".tn":  "whois.ripe.net",
    ".to":  "whois.tonic.to",
    ".tp":  "whois.domains.tl",
    ".tr":  "whois.nic.tr",
    ".com.tr":"whois.nic.tr",
    ".gov.tr":"whois.nic.tr",
    ".ua":  "whois.com.ua",
    ".com.ua":"whois.com.ua",
    ".net.ua":"whois.com.ua",
    ".com.ua": "whois.com.ua",
    ".vn.ua": "whois.com.ua",
    ".gov.ua":"whois.com.ua",
    ".kiev.ua":"whois.com.ua",
    ".in.ua":"whois.com.ua",
    ".uy": "nic.uy",
    ".uz":  "whois.cctld.uz",
    ".va":  "whois.ripe.net",
    ".vc":  "whois2.afilias-grs.net",
    ".ve":  "whois.nic.ve",
    ".gob.ve":"whois.nic.ve",
    ".edu.ve":"whois.nic.ve",
    ".org.ve":"whois.nic.ve",
    ".com.ve":"whois.nic.ve",
    ".mil.ve":"whois.nic.ve",
    ".vg":  "whois.adamsnames.tc",
    ".yu":  "whois.ripe.net",
    ".xyz": "whois.nic.xyz",
    ".co.za": "whois.registry.net.za",
    ".gov.za":"163.195.16.25",
    ".kz": 'whois.nic.kz',
    '.nc': 'whois.nc',
    ".cat": 'whois.cat',
    ".mn": "whois.nic.mn",
    ".xxx": "whois.nic.xxx",
    ".co": "whois.nic.co",
    ".com.co":"whois.nic.co",
    ".photos":"whois.donuts.co",
    ".id":'whois.pandi.or.id',
    ".or.id":'whois.pandi.or.id',
    ".co.id":'whois.pandi.or.id',
    ".go.id":'whois.pandi.or.id',
    ".net.id":'whois.pandi.or.id',
    ".web.id":"whois.pandi.or.id",
    ".kaskus.id":"whois.pandi.or.id",
    ".rs" : "whois.rnids.rs",
    ".in.rs": "whois.rnids.rs",
    ".guru":"whois.donuts.co",
    ".website":"whois.nic.website",
    ".press":"whois.nic.press",
    ".sn":"whois.nic.sn",
    ".gi":"whois2.afilias-grs.net",
    ".gov.gi":"whois2.afilias-grs.net",
    ".com.gi":"whois2.afilias-grs.net",
    ".uno":"whois.nic.uno",
    ".fm":"whois.nic.fm",
    ".gift":"whois.uniregistry.net",
    ".club":"whois.nic.club",
    ".jobs":"jobswhois.verisign-grs.com",
    ".today":"whois.donuts.co",
    ".land":"whois.donuts.co",
    ".email":"whois.donuts.co",
    ".msk.ru":"whois.ripn.net",
    ".xn--p1ai":"whois.tcinet.ru",
    ".io":"whois.nic.io",
    ".zm":"whois.nic.zm",
    ".co.zm":"whois.nic.zm",
    ".org.zm":"whois.nic.zm",
    ".com.zm":"whois.nic.zm",
    ".ac.zm":"whois.nic.zm",
    ".country":"whois-dub.mm-registry.com",
    ".im":"whois.nic.im"

}